version: '3'

services:
  confluence:
    image: atlassian/confluence-server
    container_name: confluence
    volumes:
      - confluencedata:/var/atlassian/confluence
    ports:
      - '80:8090'
      - '8091:8091'
    environment:
      - CONFLUENCE_DB_HOST=db
      - CONFLUENCE_DB_PORT=5432
      - CATALINA_OPTS=-Xms256m -Xmx1g
      - CONFLUENCE_PROXY_NAME=
      - CONFLUENCE_PROXY_PORT=
      - CONFLUENCE_PROXY_SCHEME=
      - CONFLUENCE_DELAYED_START=
      # those are preconfigurations so that we do not need to set our DB creds when installing - you can also
      # no use that and do it manually during the interactive installation
      # TODO: even though it lands in the configuration it seems to not really picked up by confluence during the installation
      - CONFLUENCE_CONFIG_PROPERTY1=hibernate.connection.driver_class
      - CONFLUENCE_CONFIG_VALUE1=org.postgresql.Driver
      - CONFLUENCE_CONFIG_PROPERTY2=hibernate.connection.password
      - CONFLUENCE_CONFIG_VALUE2=jellyfish
      - CONFLUENCE_CONFIG_PROPERTY3=hibernate.connection.url
      - CONFLUENCE_CONFIG_VALUE3=jdbc:postgresql://db/confluencedb
      - CONFLUENCE_CONFIG_PROPERTY4=hibernate.connection.username
      - CONFLUENCE_CONFIG_VALUE4=confluencedb
  db:
    image: postgres:9.6
    container_name: postgres
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=confluencedb
      - POSTGRES_PASSWORD=verybigsecretrootpassword
      - POSTGRES_DB=confluencedb
volumes:
  confluencedata:
    external: false
  postgresqldata:
    external: false